language: node_js
cache:
  directories:
  - node_modules
script:
- npm install
deploy:
  provider: s3
  bucket: 757colorcoded.org
  local_dir: src
  secret_access_key:
    secure: f2kEEMqQRigreydip1aURXYWuoQwyWzYj8dygRno9N6SD2LWeuE7cZEXk2fhhj6GDJJBLwSJwT7YwguHZCf4usWyGeZUl8xDfuNORu79QbMK9VZFtGPmp2WeZYt3x0x8O+TMA6lk9V1a7y5vX7ERM0NFSsZmXS32qoh0QtT5llqJGDnVXfLaE2CeltnrxRd4+N2xgaNC8cRcx0E28XRTwvVJPTyz790yvi9SceeLXBgfToN1F5ksZ/3UZOxpfKHkzq+MjikhDnaoRthCTz6ZpQkqFo6qwi28Rx4lz0nRwKYzVdbW48ZZ+kL81573c8RrQx7kYQ8RxYtkgQkabeDS9wAX2/OFVDQnc2o4Qefof8vuYtwWRSSytA96wk8HJjPUa8oTbBqPQm7WnxB4Mv3/vtLtFeM2r8I99tsEMyY0fPSyatbS8hik9NAzICkB9eP44JJGuSfO345IzrzBYtxoQRnocxKdf1+1fnG6/mcwXqtR4KIml9h4aNDHkgK//qt4aLS91hsTHc2UBnRN8Lm5Bh/1o3MVTbTCcbr+V6AaPGRm3BGYKsfmwg4S12ONfIeaf0O7p8LnER8HqmySoAXxDoxHAonPYii0VsbmGxkSrPKUJE4dORcEek87LoZVdhwjrIBiR9SzwI464RHas8m7AEq1uf6XppHrLjUSjIEm8v4=
  access_key_id:
    secure: QEQU3etNBSsoj6bA4R/Jj66HQ0h56SjADagsH8BEMa1ID4xdoGZChG7KyjY91wtYt46SxZe+GZZhSmHxj9Gjjlah7IcQesu9aNOY195OyDpv2Z1OnS3pinPL+dS9wt5hx7Ky0PSBaG4P/GIx7v1dx5SSjAd1xrpimtrOv7QZQO0IH2U8Tzry7l92hoab9z07AIUpkXrCyfnsiCe1MJ0ZfEh9dYk+e677YiWhk6gOr4ZHrGFZaiQzCoHyqA2Ar508Q6YweWJGQg00kZnvEkYP83gbbDHzSxB7+S1kUzZqNeFHeailmCXFwa0f8jLvN7Rrx7ROAeWMPZhYr06H8DPz2U706SPVNlbS4bM+MHJ6J4XWbQYPTFRGbGyRtgHPx481D9lNHBFrqhljH0j+y3DNsyvMgZHqduOtH7NUSvYk/ksY2qiefScX0Wte/LayOl9PeV/3DUzLzyUpI8v2qbb/mbQXvkSI/BZUP88QfuXNNHH62IYDNOaZcikhGW52rDt8ovB7lCjWS7S9JPexlc4KxyMvwiqY/dyOLTwfw5T2hlJfJNqSD0fTZSUOagNxSqT4X5S/TaC7btipy4Q/n3wd+f6qn4XmNAQfoj1bgq35V16yD/ELekZIdaFskpeK5rbLpusPPrj2g+y1Ti6fjkvnLScKuHPHn2QSCGHeHKltP48=
  skip_cleanup: true
  region: us-east-1
  acl: public_read
  on:
    repo: 757colorcoded/website
